export interface SeedEntry {
  name: string;
  parentName: string | null;
}

export const seedData: SeedEntry[] = [
  // ── Electronics (L0) ────────────────────────────────────────────────────
  { name: 'Electronics', parentName: null },
  { name: 'Mobile & Tablets', parentName: 'Electronics' },
  { name: 'Smartphones', parentName: 'Mobile & Tablets' },
  { name: 'Android Phones', parentName: 'Smartphones' },
  { name: 'iOS Phones', parentName: 'Smartphones' },
  { name: 'Budget Phones', parentName: 'Smartphones' },
  { name: 'Flagship Phones', parentName: 'Smartphones' },
  { name: 'Tablets', parentName: 'Mobile & Tablets' },
  { name: 'Android Tablets', parentName: 'Tablets' },
  { name: 'iPad', parentName: 'Tablets' },
  { name: 'E-Readers', parentName: 'Tablets' },
  { name: 'Accessories', parentName: 'Electronics' },
  { name: 'Wearable Accessories', parentName: 'Accessories' },
  { name: 'Smart Watch', parentName: 'Wearable Accessories' },
  { name: 'Fitness Bands', parentName: 'Wearable Accessories' },
  { name: 'Smart Glasses', parentName: 'Wearable Accessories' },
  { name: 'Phone Cases', parentName: 'Accessories' },
  { name: 'Screen Protectors', parentName: 'Accessories' },
  { name: 'Chargers & Cables', parentName: 'Accessories' },
  { name: 'Wireless Chargers', parentName: 'Chargers & Cables' },
  { name: 'USB-C Cables', parentName: 'Chargers & Cables' },
  { name: 'Power Banks', parentName: 'Accessories' },
  { name: 'Computers & Laptops', parentName: 'Electronics' },
  { name: 'Laptops', parentName: 'Computers & Laptops' },
  { name: 'Gaming Laptops', parentName: 'Laptops' },
  { name: 'Ultrabooks', parentName: 'Laptops' },
  { name: 'Business Laptops', parentName: 'Laptops' },
  { name: 'Chromebooks', parentName: 'Laptops' },
  { name: 'Desktops', parentName: 'Computers & Laptops' },
  { name: 'Gaming Desktops', parentName: 'Desktops' },
  { name: 'All-in-One PCs', parentName: 'Desktops' },
  { name: 'Mini PCs', parentName: 'Desktops' },
  { name: 'Monitors', parentName: 'Computers & Laptops' },
  { name: '4K Monitors', parentName: 'Monitors' },
  { name: 'Gaming Monitors', parentName: 'Monitors' },
  { name: 'Ultrawide Monitors', parentName: 'Monitors' },
  { name: 'Computer Peripherals', parentName: 'Computers & Laptops' },
  { name: 'Keyboards', parentName: 'Computer Peripherals' },
  { name: 'Mechanical Keyboards', parentName: 'Keyboards' },
  { name: 'Wireless Keyboards', parentName: 'Keyboards' },
  { name: 'Mice', parentName: 'Computer Peripherals' },
  { name: 'Gaming Mice', parentName: 'Mice' },
  { name: 'Webcams', parentName: 'Computer Peripherals' },
  { name: 'Headsets', parentName: 'Computer Peripherals' },
  { name: 'Storage', parentName: 'Computers & Laptops' },
  { name: 'SSDs', parentName: 'Storage' },
  { name: 'Hard Drives', parentName: 'Storage' },
  { name: 'USB Flash Drives', parentName: 'Storage' },
  { name: 'Memory Cards', parentName: 'Storage' },
  { name: 'Networking', parentName: 'Electronics' },
  { name: 'Routers', parentName: 'Networking' },
  { name: 'Wi-Fi 6 Routers', parentName: 'Routers' },
  { name: 'Mesh Routers', parentName: 'Routers' },
  { name: 'Network Switches', parentName: 'Networking' },
  { name: 'Network Adapters', parentName: 'Networking' },
  { name: 'Cameras', parentName: 'Electronics' },
  { name: 'DSLR Cameras', parentName: 'Cameras' },
  { name: 'Mirrorless Cameras', parentName: 'Cameras' },
  { name: 'Action Cameras', parentName: 'Cameras' },
  { name: 'Dashcams', parentName: 'Cameras' },
  { name: 'Security Cameras', parentName: 'Cameras' },
  { name: 'Camera Lenses', parentName: 'Cameras' },
  { name: 'Wide Angle Lenses', parentName: 'Camera Lenses' },
  { name: 'Telephoto Lenses', parentName: 'Camera Lenses' },
  { name: 'Audio', parentName: 'Electronics' },
  { name: 'Headphones', parentName: 'Audio' },
  { name: 'Over-Ear Headphones', parentName: 'Headphones' },
  { name: 'In-Ear Headphones', parentName: 'Headphones' },
  { name: 'True Wireless Earbuds', parentName: 'Headphones' },
  { name: 'Noise Cancelling Headphones', parentName: 'Headphones' },
  { name: 'Speakers', parentName: 'Audio' },
  { name: 'Bluetooth Speakers', parentName: 'Speakers' },
  { name: 'Smart Speakers', parentName: 'Speakers' },
  { name: 'Soundbars', parentName: 'Speakers' },
  { name: 'Microphones', parentName: 'Audio' },
  { name: 'USB Microphones', parentName: 'Microphones' },
  { name: 'Condenser Microphones', parentName: 'Microphones' },

  // ── Appliances (L0) ──────────────────────────────────────────────────────
  { name: 'Appliances', parentName: null },
  { name: 'Home Appliances', parentName: 'Appliances' },
  { name: 'Television', parentName: 'Home Appliances' },
  { name: 'OLED TVs', parentName: 'Television' },
  { name: 'QLED TVs', parentName: 'Television' },
  { name: 'Smart TVs', parentName: 'Television' },
  { name: 'Refrigerators', parentName: 'Home Appliances' },
  { name: 'Double Door Refrigerators', parentName: 'Refrigerators' },
  { name: 'Side-by-Side Refrigerators', parentName: 'Refrigerators' },
  { name: 'Mini Fridges', parentName: 'Refrigerators' },
  { name: 'Washing Machines', parentName: 'Home Appliances' },
  { name: 'Front Load Washers', parentName: 'Washing Machines' },
  { name: 'Top Load Washers', parentName: 'Washing Machines' },
  { name: 'Washer Dryer Combos', parentName: 'Washing Machines' },
  { name: 'Air Conditioners', parentName: 'Home Appliances' },
  { name: 'Split ACs', parentName: 'Air Conditioners' },
  { name: 'Window ACs', parentName: 'Air Conditioners' },
  { name: 'Portable ACs', parentName: 'Air Conditioners' },
  { name: 'Kitchen Appliances', parentName: 'Appliances' },
  { name: 'Microwaves', parentName: 'Kitchen Appliances' },
  { name: 'Solo Microwaves', parentName: 'Microwaves' },
  { name: 'Convection Microwaves', parentName: 'Microwaves' },
  { name: 'Blenders', parentName: 'Kitchen Appliances' },
  { name: 'Countertop Blenders', parentName: 'Blenders' },
  { name: 'Immersion Blenders', parentName: 'Blenders' },
  { name: 'Coffee Machines', parentName: 'Kitchen Appliances' },
  { name: 'Espresso Machines', parentName: 'Coffee Machines' },
  { name: 'Drip Coffee Makers', parentName: 'Coffee Machines' },
  { name: 'Pod Coffee Machines', parentName: 'Coffee Machines' },
  { name: 'Air Fryers', parentName: 'Kitchen Appliances' },
  { name: 'Dishwashers', parentName: 'Kitchen Appliances' },
  { name: 'Toasters', parentName: 'Kitchen Appliances' },
  { name: 'Food Processors', parentName: 'Kitchen Appliances' },

  // ── Fashion (L0) ─────────────────────────────────────────────────────────
  { name: 'Fashion', parentName: null },
  { name: "Men's Fashion", parentName: 'Fashion' },
  { name: "Men's Clothing", parentName: "Men's Fashion" },
  { name: "Men's T-Shirts", parentName: "Men's Clothing" },
  { name: "Men's Shirts", parentName: "Men's Clothing" },
  { name: "Men's Trousers", parentName: "Men's Clothing" },
  { name: "Men's Jeans", parentName: "Men's Clothing" },
  { name: "Men's Jackets", parentName: "Men's Clothing" },
  { name: "Men's Footwear", parentName: "Men's Fashion" },
  { name: "Men's Sneakers", parentName: "Men's Footwear" },
  { name: "Men's Formal Shoes", parentName: "Men's Footwear" },
  { name: "Men's Sandals", parentName: "Men's Footwear" },
  { name: "Men's Accessories", parentName: "Men's Fashion" },
  { name: "Men's Watches", parentName: "Men's Accessories" },
  { name: "Men's Wallets", parentName: "Men's Accessories" },
  { name: "Men's Belts", parentName: "Men's Accessories" },
  { name: "Women's Fashion", parentName: 'Fashion' },
  { name: "Women's Clothing", parentName: "Women's Fashion" },
  { name: "Women's Tops", parentName: "Women's Clothing" },
  { name: "Women's Dresses", parentName: "Women's Clothing" },
  { name: "Women's Skirts", parentName: "Women's Clothing" },
  { name: "Women's Jeans", parentName: "Women's Clothing" },
  { name: "Women's Jackets", parentName: "Women's Clothing" },
  { name: "Women's Footwear", parentName: "Women's Fashion" },
  { name: "Women's Heels", parentName: "Women's Footwear" },
  { name: "Women's Flats", parentName: "Women's Footwear" },
  { name: "Women's Sneakers", parentName: "Women's Footwear" },
  { name: "Women's Accessories", parentName: "Women's Fashion" },
  { name: "Women's Handbags", parentName: "Women's Accessories" },
  { name: "Women's Jewellery", parentName: "Women's Accessories" },
  { name: "Women's Watches", parentName: "Women's Accessories" },
  { name: "Women's Sunglasses", parentName: "Women's Accessories" },
  { name: "Kids' Fashion", parentName: 'Fashion' },
  { name: "Boys' Clothing", parentName: "Kids' Fashion" },
  { name: "Girls' Clothing", parentName: "Kids' Fashion" },
  { name: "Kids' Footwear", parentName: "Kids' Fashion" },
  { name: "Kids' Accessories", parentName: "Kids' Fashion" },

  // ── Health & Beauty (L0) ─────────────────────────────────────────────────
  { name: 'Health & Beauty', parentName: null },
  { name: 'Skincare', parentName: 'Health & Beauty' },
  { name: 'Moisturisers', parentName: 'Skincare' },
  { name: 'Face Wash', parentName: 'Skincare' },
  { name: 'Serums', parentName: 'Skincare' },
  { name: 'Sunscreen', parentName: 'Skincare' },
  { name: 'Toners', parentName: 'Skincare' },
  { name: 'Hair Care', parentName: 'Health & Beauty' },
  { name: 'Shampoos', parentName: 'Hair Care' },
  { name: 'Conditioners', parentName: 'Hair Care' },
  { name: 'Hair Oils', parentName: 'Hair Care' },
  { name: 'Hair Masks', parentName: 'Hair Care' },
  { name: 'Hair Styling', parentName: 'Hair Care' },
  { name: 'Makeup', parentName: 'Health & Beauty' },
  { name: 'Foundation', parentName: 'Makeup' },
  { name: 'Lipstick', parentName: 'Makeup' },
  { name: 'Mascara', parentName: 'Makeup' },
  { name: 'Eyeshadow', parentName: 'Makeup' },
  { name: 'Blush', parentName: 'Makeup' },
  { name: 'Fragrances', parentName: 'Health & Beauty' },
  { name: "Men's Perfumes", parentName: 'Fragrances' },
  { name: "Women's Perfumes", parentName: 'Fragrances' },
  { name: 'Personal Care', parentName: 'Health & Beauty' },
  { name: 'Oral Care', parentName: 'Personal Care' },
  { name: 'Electric Toothbrushes', parentName: 'Oral Care' },
  { name: 'Toothpaste', parentName: 'Oral Care' },
  { name: 'Body Care', parentName: 'Personal Care' },
  { name: 'Body Wash', parentName: 'Body Care' },
  { name: 'Lotions', parentName: 'Body Care' },
  { name: 'Health Monitors', parentName: 'Health & Beauty' },
  { name: 'Blood Pressure Monitors', parentName: 'Health Monitors' },
  { name: 'Glucometers', parentName: 'Health Monitors' },
  { name: 'Pulse Oximeters', parentName: 'Health Monitors' },
  { name: 'Weighing Scales', parentName: 'Health Monitors' },

  // ── Sports & Outdoors (L0) ────────────────────────────────────────────────
  { name: 'Sports & Outdoors', parentName: null },
  { name: 'Fitness Equipment', parentName: 'Sports & Outdoors' },
  { name: 'Treadmills', parentName: 'Fitness Equipment' },
  { name: 'Exercise Bikes', parentName: 'Fitness Equipment' },
  { name: 'Dumbbells', parentName: 'Fitness Equipment' },
  { name: 'Resistance Bands', parentName: 'Fitness Equipment' },
  { name: 'Yoga Mats', parentName: 'Fitness Equipment' },
  { name: 'Outdoor Sports', parentName: 'Sports & Outdoors' },
  { name: 'Cycling', parentName: 'Outdoor Sports' },
  { name: 'Mountain Bikes', parentName: 'Cycling' },
  { name: 'Road Bikes', parentName: 'Cycling' },
  { name: 'Cycle Accessories', parentName: 'Cycling' },
  { name: 'Running', parentName: 'Outdoor Sports' },
  { name: 'Running Shoes', parentName: 'Running' },
  { name: 'Running Apparel', parentName: 'Running' },
  { name: 'Swimming', parentName: 'Outdoor Sports' },
  { name: 'Swimwear', parentName: 'Swimming' },
  { name: 'Swimming Goggles', parentName: 'Swimming' },
  { name: 'Team Sports', parentName: 'Sports & Outdoors' },
  { name: 'Cricket', parentName: 'Team Sports' },
  { name: 'Cricket Bats', parentName: 'Cricket' },
  { name: 'Cricket Balls', parentName: 'Cricket' },
  { name: 'Cricket Protective Gear', parentName: 'Cricket' },
  { name: 'Football', parentName: 'Team Sports' },
  { name: 'Footballs', parentName: 'Football' },
  { name: 'Football Boots', parentName: 'Football' },
  { name: 'Football Jerseys', parentName: 'Football' },
  { name: 'Badminton', parentName: 'Team Sports' },
  { name: 'Badminton Rackets', parentName: 'Badminton' },
  { name: 'Shuttlecocks', parentName: 'Badminton' },

  // ── Books & Stationery (L0) ──────────────────────────────────────────────
  { name: 'Books & Stationery', parentName: null },
  { name: 'Books', parentName: 'Books & Stationery' },
  { name: 'Fiction', parentName: 'Books' },
  { name: 'Thriller', parentName: 'Fiction' },
  { name: 'Science Fiction', parentName: 'Fiction' },
  { name: 'Romance', parentName: 'Fiction' },
  { name: 'Fantasy', parentName: 'Fiction' },
  { name: 'Non-Fiction', parentName: 'Books' },
  { name: 'Self Help', parentName: 'Non-Fiction' },
  { name: 'Biography', parentName: 'Non-Fiction' },
  { name: 'History', parentName: 'Non-Fiction' },
  { name: 'Science & Technology', parentName: 'Non-Fiction' },
  { name: 'Business & Finance', parentName: 'Non-Fiction' },
  { name: "Children's Books", parentName: 'Books' },
  { name: 'Picture Books', parentName: "Children's Books" },
  { name: 'Educational Books', parentName: "Children's Books" },
  { name: 'Stationery', parentName: 'Books & Stationery' },
  { name: 'Notebooks', parentName: 'Stationery' },
  { name: 'Pens & Pencils', parentName: 'Stationery' },
  { name: 'Art Supplies', parentName: 'Stationery' },
  { name: 'Sketch Pens', parentName: 'Art Supplies' },
  { name: 'Watercolours', parentName: 'Art Supplies' },
  { name: 'Canvases', parentName: 'Art Supplies' },

  // ── Toys & Games (L0) ────────────────────────────────────────────────────
  { name: 'Toys & Games', parentName: null },
  { name: 'Action Figures', parentName: 'Toys & Games' },
  { name: 'Superhero Figures', parentName: 'Action Figures' },
  { name: 'Anime Figures', parentName: 'Action Figures' },
  { name: 'Building Blocks', parentName: 'Toys & Games' },
  { name: 'LEGO Sets', parentName: 'Building Blocks' },
  { name: 'Magnetic Tiles', parentName: 'Building Blocks' },
  { name: 'Board Games', parentName: 'Toys & Games' },
  { name: 'Strategy Games', parentName: 'Board Games' },
  { name: 'Card Games', parentName: 'Board Games' },
  { name: 'Puzzles', parentName: 'Board Games' },
  { name: 'Video Games', parentName: 'Toys & Games' },
  { name: 'PlayStation Games', parentName: 'Video Games' },
  { name: 'Xbox Games', parentName: 'Video Games' },
  { name: 'Nintendo Switch Games', parentName: 'Video Games' },
  { name: 'PC Games', parentName: 'Video Games' },
  { name: 'Gaming Consoles', parentName: 'Toys & Games' },
  { name: 'PlayStation', parentName: 'Gaming Consoles' },
  { name: 'Xbox', parentName: 'Gaming Consoles' },
  { name: 'Nintendo Switch', parentName: 'Gaming Consoles' },
  { name: 'Gaming Accessories', parentName: 'Toys & Games' },
  { name: 'Controllers', parentName: 'Gaming Accessories' },
  { name: 'Gaming Chairs', parentName: 'Gaming Accessories' },
  { name: 'Gaming Headsets', parentName: 'Gaming Accessories' },
];
